name: deploy-vercel
on:
  push:
    branches: [ "main" ]

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 12
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'npm' }
      - run: npm ci
      - run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'npm' }
      - run: npm ci

      - name: Validate Vercel env
        shell: bash
        run: |
          set -eu
          [ -n "${VERCEL_TOKEN:-}" ] || { echo "VERCEL_TOKEN fehlt"; exit 1; }
          [ -n "${VERCEL_ORG_ID:-}" ] || { echo "VERCEL_ORG_ID fehlt"; exit 1; }
          [ -n "${VERCEL_PROJECT_ID:-}" ] || { echo "VERCEL_PROJECT_ID fehlt"; exit 1; }

      - name: vercel pull (prod)
        run: npx --yes vercel@latest pull --yes --environment=production \
               --token "$VERCEL_TOKEN" --project "$VERCEL_PROJECT_ID" --scope "$VERCEL_ORG_ID"

      - name: vercel build (prebuilt)
        run: npx --yes vercel@latest build --prod \
               --token "$VERCEL_TOKEN" --project "$VERCEL_PROJECT_ID" --scope "$VERCEL_ORG_ID"

      - name: vercel deploy (prebuilt to prod)
        run: npx --yes vercel@latest deploy --prebuilt --prod \
               --token "$VERCEL_TOKEN" --project "$VERCEL_PROJECT_ID" --scope "$VERCEL_ORG_ID"
