name: deploy
on:
  push:
    branches: [ "main" ]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'npm' }
      - run: npm ci
      - run: npm run build
  trigger-vercel:
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deploy Hook
        run: curl -s -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"
